## Coursera Capstone Project Week 3 Part 2

#### By Nattapol Pataraoureeruk

Step 0: Previously from part 1 -------------------------------------------------------------------------------------------------------------------------------

In [1]:
import numpy as np
import pandas as pd
import requests #Get URL
import bs4 as bs #Beautiful Soup
import lxml.html as lh

url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
resquest = requests.get(url)
bsoup = bs.BeautifulSoup(resquest.content, 'lxml')
table = bsoup.find_all('table')[0]
df = pd.read_html(str(table))
data = pd.read_json(df[0].to_json(orient='records'))

# Ignore cells with a borough that is Not assigned
data_2 = data[data['Borough']!='Not assigned']

# Grouping Data
data_3 = data_2.groupby(['Borough','Postal Code'], as_index=False).agg(','.join)

# In case a cell has a borough but a Not assigned  neighborhood, then the neighborhood will be the same as the borough
data_3['Neighbourhood'] = np.where(data_3['Neighbourhood']=='Not assigned', data_3['Borough'],data_3['Neighbourhood'] )

data_3.head()

           Borough Postal Code                      Neighbourhood
0  Central Toronto         M4N                      Lawrence Park
1  Central Toronto         M4P                   Davisville North
2  Central Toronto         M4R  North Toronto West, Lawrence Park
3  Central Toronto         M4S                         Davisville
4  Central Toronto         M4T        Moore Park, Summerhill East

End of part 1 ----------------------------------------------------------------------------------------------------------------

## Question 2 started below

Step 1: Getting data from CSV

In [4]:
geo_url = "https://cocl.us/Geospatial_data"
geo_data = pd.read_csv(geo_url)

geo_data

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

Step 2: Merging data together

In [9]:
Merged_data = pd.merge(data_3, geo_data, on='Postal Code')
Merged_data[['Postal Code','Borough','Neighbourhood','Latitude','Longitude']]

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M4N,Central Toronto,Lawrence Park,43.728020,-79.388790
1,M4P,Central Toronto,Davisville North,43.712751,-79.390197
2,M4R,Central Toronto,"North Toronto West, Lawrence Park",43.715383,-79.405678
3,M4S,Central Toronto,Davisville,43.704324,-79.388790
4,M4T,Central Toronto,"Moore Park, Summerhill East",43.689574,-79.383160
...,...,...,...,...,...
98,M6C,York,Humewood-Cedarvale,43.693781,-79.428191
99,M6E,York,Caledonia-Fairbanks,43.689026,-79.453512
100,M6M,York,"Del Ray, Mount Dennis, Keelsdale and Silverthorn",43.691116,-79.476013
101,M6N,York,"Runnymede, The Junction North",43.673185,-79.487262
102,M9N,York,Weston,43.706876,-79.518188